services:
    comfino-prestashop-php:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        working_dir: /comfino-prestashop
        tty: true
        volumes:
            - ./:/comfino-prestashop
            - ~/.composer:/home/comfino/.composer
