services:
    Comfino\Controller\OrderController:
        class: Comfino\Controller\OrderController
        parent: PrestaShopBundle\Controller\Admin\Sell\Order\OrderController

    prestashop.core.form.choice_provider.order_state_by_id:
        class: Comfino\Form\ChoiceProvider\OrderStateByIdChoiceProvider
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
            - '@prestashop.adapter.data_provider.order_state'
            - '@prestashop.core.util.color_brightness_calculator'
            - '@translator'

    form.type.order.update_order_status:
        class: Comfino\Form\Admin\Sell\Order\UpdateOrderStatusType
        arguments:
            - '@prestashop.core.form.choice_provider.order_state_by_id'
            - '@=service("prestashop.core.form.choice_provider.order_state_by_id").getChoicesAttributes()'
        tags:
            - { name: form.type }

    prestashop.adapter.order.command_handler.bulk_change_order_status_handler:
        class: Comfino\Adapter\Order\CommandHandler\BulkChangeOrderStatusHandler
        tags:
            - name: tactician.handler
              command: 'PrestaShop\PrestaShop\Core\Domain\Order\Command\BulkChangeOrderStatusCommand'

    prestashop.adapter.order.command_handler.update_order_status_handler:
        class: Comfino\Adapter\Order\CommandHandler\UpdateOrderStatusHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\Order\Command\UpdateOrderStatusCommand
